# Check against previous runs?
check_previous: False

# Database configurations
connections: 
  edit: "S:\\GIS\\Share\\DatabaseConnections\\SQLGISProd3\\gisscr on gisprod3.sde"
  read: "S:\\GIS\\Share\\DatabaseConnections\\SQLGISProd3\\gis on gisprod3.sde"

# Email
password: "password"
recipients:
  - "nestlerj@bouldercolorado.gov"
  - "jeffreyb@bouldercolorado.gov"
  - "salmone@bouldercolorado.gov"
  - "simpsonj@bouldercolorado.gov"
  - "gregoryk@bouldercolorado.gov"

# Logging Configurations
logging:
  version: 1
  formatters:
    only:
      format: '%(asctime)s.%(msecs)03d : %(levelname)s : %(message)s'
      datefmt: '%m/%d/%Y %H:%M:%S'
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: only
      stream: ext://sys.stdout
    file:
      class: logging.FileHandler
      level: INFO
      formatter: only
      filename: '.\\log\\impervious.log'
    email:
      class: logging.handlers.SMTPHandler
      mailhost: ["smtp.office365.com", 587]
      fromaddr: "noreply@bouldercolorado.gov"
      toaddrs: ["nestj1@bouldercolorado.gov"]
      subject: "An error halted the impervious script"
      credentials: ["noreply@bouldercolorado.gov", "password"]
      secure: []
      level: ERROR
      formatter: only
  loggers:
    __main__:
      level: INFO
      handlers: [console, file, email]
